In [5]:
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt 

in_data = loadmat('movie.mat')
#loadmat() loads a matlab workspace into a python dictionary, where the names of the variables are the keys 
#in the dictionary.  To see what variables are loaded, uncomment the line below: 
#print([key for key in in_data])

M = in_data['M']
print(M)

[[ 4  7  2  8  7  4  2]
 [ 9  3  5  6 10  5  5]
 [ 4  8  3  7  6  4  1]
 [ 9  2  6  5  9  5  4]
 [ 4  9  2  8  7  4  1]]


In [6]:
# Problem 3(a)
np.linalg.matrix_rank(M)
# rank(M) = 5

5

In [ ]:
# Problem 3(b)
# M = TW

# M is 5 x 7
# T is 5 x r
# W is r x 7

In [ ]:
# Problem 3(c)

# t1 , first taste vector:
# t1 = 1/sqrt(5) [1 1 1 ... 1]

# w should be [sum of column]
# w 1,j