In [4]:
import numpy as np
v1 = np.array([1,2,3])
u1 = np.array([2,3,4])
sigma1 = 5
A = sigma1 * np.outer(u1,v1)


In [35]:
b_k = np.random.randn(3)
B = A.T @ A
b_k

array([-1.73825704, -0.05887893,  2.01450159])

In [141]:
b_k = np.random.randn(3)
B = A.T @ A
b_k

for k in range(1,6):
    b_k = (B @ b_k) / np.linalg.norm(B @ b_k)
    print(f"Iteration {k}: {b_k}")

Iteration 1: [0.26726124 0.53452248 0.80178373]
Iteration 2: [0.26726124 0.53452248 0.80178373]
Iteration 3: [0.26726124 0.53452248 0.80178373]
Iteration 4: [0.26726124 0.53452248 0.80178373]
Iteration 5: [0.26726124 0.53452248 0.80178373]


In [114]:
A = np.array([[1,2,3],[2,4,6],[3,6,9]])
A_rand = np.random.rand(3,3)
np.linalg.matrix_rank(A_rand)

3

In [ ]:
# Part 2 - Full Rank Matrix

A_rand = np.random.rand(3,3)

In [163]:
# When you use A A^T, you get the eigenvector of A A^T associated 
# with the largest eigenvalue. (The largest right singular vector)

A = np.array([[1,2,3],[2,4,6],[3,6,9]])
A_rand = np.random.rand(3,3)
AAT_rand = A_rand @ A_rand.T

b_0 = np.random.randn(3)
b_k = b_0;

for k in range(1,10):
    b_k = (AAT_rand @ b_k) / np.linalg.norm(AAT_rand @ b_k)
    print(f"Iteration {k}: {b_k}")
    
print('\n')
print(np.linalg.eig(AAT_rand)[0], "\n\n\n", np.linalg.eig(AAT_rand)[1])

Iteration 1: [-0.64209632 -0.4473858  -0.62254178]
Iteration 2: [-0.62665758 -0.50727601 -0.59158375]
Iteration 3: [-0.62531337 -0.51188937 -0.58902671]
Iteration 4: [-0.62520702 -0.512251   -0.58882517]
Iteration 5: [-0.62519867 -0.5122794  -0.58880934]
Iteration 6: [-0.62519801 -0.51228163 -0.5888081 ]
Iteration 7: [-0.62519796 -0.5122818  -0.588808  ]
Iteration 8: [-0.62519796 -0.51228182 -0.588808  ]
Iteration 9: [-0.62519796 -0.51228182 -0.58880799]


[3.75022738e+00 1.08433958e-03 2.94488590e-01] 


 [[ 0.62519796  0.7396984   0.24894535]
 [ 0.51228182 -0.14829043 -0.84591802]
 [ 0.58880799 -0.65639639  0.47164492]]


In [164]:
# When you use A^T A, you get the eigenvector of A^T A associated 
# with the largest eigenvalue. (The largest left singular vector)

ATA_rand = A_rand.T @ A_rand

b_0 = np.random.randn(3)
b_k = b_0;

for k in range(1,10):
    b_k = (ATA_rand @ b_k) / np.linalg.norm(ATA_rand @ b_k)
    print(f"Iteration {k}: {b_k}")
    
print('\n')
print(np.linalg.eig(ATA_rand)[0], "\n\n\n", np.linalg.eig(ATA_rand)[1])

Iteration 1: [-0.76507102 -0.1312568  -0.63042683]
Iteration 2: [-0.78149751 -0.22645541 -0.58136012]
Iteration 3: [-0.78237272 -0.2338926  -0.57722368]
Iteration 4: [-0.78243902 -0.23447592 -0.57689707]
Iteration 5: [-0.78244421 -0.23452172 -0.57687141]
Iteration 6: [-0.78244462 -0.23452531 -0.5768694 ]
Iteration 7: [-0.78244465 -0.2345256  -0.57686924]
Iteration 8: [-0.78244465 -0.23452562 -0.57686923]
Iteration 9: [-0.78244465 -0.23452562 -0.57686922]


[3.75022738e+00 1.08433958e-03 2.94488590e-01] 


 [[ 0.78244465  0.61490069 -0.09837433]
 [ 0.23452562 -0.43732343 -0.86818543]
 [ 0.57686922 -0.65623575  0.48639135]]


In [165]:
# When you use A, you get the eigenvector of A associated 
# with the largest eigenvalue.

ATA_rand = A_rand.T @ A_rand

b_0 = np.random.randn(3)
b_k = b_0;

for k in range(1,10):
    b_k = (ATA_rand @ b_k) / np.linalg.norm(ATA_rand @ b_k)
    print(f"Iteration {k}: {b_k}")

print('\n')
print(np.linalg.eig(ATA_rand)[0], "\n\n\n", np.linalg.eig(ATA_rand)[1])

Iteration 1: [-0.78651342 -0.27760667 -0.55166219]
Iteration 2: [-0.78282584 -0.23794107 -0.57495021]
Iteration 3: [-0.78247502 -0.23479396 -0.57671886]
Iteration 4: [-0.78244704 -0.23454669 -0.57685742]
Iteration 5: [-0.78244484 -0.23452727 -0.5768683 ]
Iteration 6: [-0.78244467 -0.23452575 -0.57686915]
Iteration 7: [-0.78244465 -0.23452563 -0.57686922]
Iteration 8: [-0.78244465 -0.23452562 -0.57686922]
Iteration 9: [-0.78244465 -0.23452562 -0.57686922]


[3.75022738e+00 1.08433958e-03 2.94488590e-01] 


 [[ 0.78244465  0.61490069 -0.09837433]
 [ 0.23452562 -0.43732343 -0.86818543]
 [ 0.57686922 -0.65623575  0.48639135]]
